### ISSUE TITLE
AttributeError: 'Table' object has no attribute 'purge'

### ISSUE THREAD

**Issue by christophchamp** [ncrocfer/whatportis#20]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

```
$ pip3 -V
pip 20.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```

```
$ sudo pip3 install whatportis
$ whatportis redis
Database not found, doing first import...
Downloading https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv...
Populating database...
Traceback (most recent call last):
  File "/usr/local/bin/whatportis", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/whatportis/cli.py", line 124, in run
    populate_db()
  File "/usr/local/lib/python3.6/dist-packages/whatportis/cli.py", line 63, in populate_db
    db.purge()
  File "/usr/local/lib/python3.6/dist-packages/tinydb/database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge'
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/foobar/.whatportis_db.json' mode='r+' encoding='UTF-8'>
```

**Comment by ncrocfer** [comment]
Breaking change in TinyDB lib : https://tinydb.readthedocs.io/en/latest/upgrade.html#version-4-0

> Replace TinyDB.purge_table(...) with TinyDB.drop_table(...)

I will fix the requirements to avoid this in the future, thanks for the report !

**Comment by ncrocfer** [comment]
Fixed in the new release :

```
$ whatportis --version
whatportis, version 0.8.1
$ whatportis redis
Database not found, doing first import...
Downloading https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv...
Populating database...
14216 ports imported.
+-------+------+----------+---------------------------------------+
| Name  | Port | Protocol | Description                           |
+-------+------+----------+---------------------------------------+
| redis | 6379 |   tcp    | An advanced key-value cache and store |
+-------+------+----------+---------------------------------------+
```
